name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t xcpo/medical-clinical-ahoy:latest .

      - name: Push Docker image to Docker Hub
        run: docker push xcpo/medical-clinical-ahoy:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 54.162.129.81
          username: ec2-user
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/medical-clinical
            docker compose pull
            docker compose up -d
